In [ ]:
import numpy as np
import math
print(np.__version__)

1.26.4


In [ ]:
arr = np.array([1,1.2,"str"])
print(arr, type(arr), arr.dtype, len(arr))

['1' '1.2' 'str'] <class 'numpy.ndarray'> <U32 3


In [ ]:
print(arr[2][2])
print(arr[2][1:])

r
tr


In [ ]:
print(arr.shape, arr.ndim, len(arr.shape))

(3,) 1 1


In [ ]:
distance = np.array([1,6,3,8])
time = np.array([3,6,10,2])

speed = distance/time
print(speed, type(speed), speed.ndim, speed.size)

[0.33333333 1.         0.3        4.        ] <class 'numpy.ndarray'> 1 4


In [ ]:
arr2 = np.array(["NYC", "LA", "MIAMI", "HOUSTON"])
print(arr2.size, arr2.ndim, len(arr2))


4 1 4


In [ ]:
arr3 = np.array([["NYC", "LA", "MIAMI", "HOUSTON"], 
                 ["NY", "CA", "FL", "TX"]], dtype = "<U20")
print(arr3.size, arr3.ndim, len(arr3), arr3.shape, "\n", arr3)

8 2 2 (2, 4) 
 [['NYC' 'LA' 'MIAMI' 'HOUSTON']
 ['NY' 'CA' 'FL' 'TX']]


In [ ]:
print(arr3[0,2])
print(arr3[0, 3][3:5])

MIAMI
ST


In [ ]:
print("FL" in arr3)

True


In [ ]:
arr4 = arr3.view()
#print(arr4)
arr4[0,2] = "Hello World"
print(arr4, "\n", arr3)

[['NYC' 'LA' 'Hello World' 'HOUSTON']
 ['NY' 'CA' 'FL' 'TX']] 
 [['NYC' 'LA' 'Hello World' 'HOUSTON']
 ['NY' 'CA' 'FL' 'TX']]


In [ ]:
arr5 = arr3.copy()
arr5[0,2] = "Hello World"
print(arr5, "\n", arr3)

[['NYC' 'LA' 'Hello World' 'HOUSTON']
 ['NY' 'CA' 'FL' 'TX']] 
 [['NYC' 'LA' 'Hello World' 'HOUSTON']
 ['NY' 'CA' 'FL' 'TX']]


In [ ]:
arr6 = np.array([1,2,3,4,5])
print(np.power(arr6, 3))

[  1   8  27  64 125]


In [ ]:
arr7 = np.array([[0,2,5,4,7,6], [6,8,16,14,11,23]])

#flattening
flat = arr7.ravel()
print(flat, flat.shape, flat.ndim)

arr8 = arr7.reshape((3,4))
print("\n",arr8, arr8.shape)
print(arr8[2,1], arr8.size)

arr9 = arr7.reshape((3,2,2))
print("\n",arr9)
print(arr9.T, arr9.T.shape)


[ 0  2  5  4  7  6  6  8 16 14 11 23] (12,) 1

 [[ 0  2  5  4]
 [ 7  6  6  8]
 [16 14 11 23]] (3, 4)
14 12

 [[[ 0  2]
  [ 5  4]]

 [[ 7  6]
  [ 6  8]]

 [[16 14]
  [11 23]]]
[[[ 0  7 16]
  [ 5  6 11]]

 [[ 2  6 14]
  [ 4  8 23]]] (2, 2, 3)


In [ ]:
arr10 = np.array([[1,2], 
                  [3,4]])

arr11 = np.array([[5,6], 
                  [7,8]])

print(arr10+arr11,"\n\n", arr10 @ arr11)
print("\n", arr10 * arr11)

[[ 6  8]
 [10 12]] 

 [[19 22]
 [43 50]]

 [[ 5 12]
 [21 32]]


In [ ]:
arr12, arr13, arr14, arr15 = np.split(flat, 4)

print(arr12, arr13, arr14, arr15)

[0 2 5] [4 7 6] [ 6  8 16] [14 11 23]


In [ ]:
arr16 = np.array([1,2, 0, 3, -1, 4,5,6,70])
even = np.where(arr16 % 2 == 0)



#print(arr16[even[0]:even[-1]])

sort = np.searchsorted(arr16, 5)
print(sort)


6


In [ ]:
arr16_sorted = sorted(arr16)
print(arr16_sorted)

arr17 = sorted(np.array(["Miami", "NYC", "California"]))
print(sorted(arr17))

arr18 = np.array([False, True, False, True, True])
print(sorted(arr18))

arr19 = np.array([[10, 7, 14], [19, 4, 2]])
print(np.argsort(arr19))

[-1, 0, 1, 2, 3, 4, 5, 6, 70]
['California', 'Miami', 'NYC']
[False, False, True, True, True]
[[1 0 2]
 [2 1 0]]


In [ ]:
def func1(x, y):
    return x*y + x + y

func1 = np.frompyfunc(func1, 2,1)

print(func1([11,12,13], [21,22,23]))

a  = 15.126345, 5.8234556
print(np.around(a))
rnd = np.around(a, 2)
print(rnd)

print(np.floor(a), np.ceil(a))



[263 298 335]
[15.  6.]
[15.13  5.82]
[15.  5.] [16.  6.]


In [ ]:
degrees = np.array([150, 360, 90, 45])

radians = np.deg2rad(degrees)

print(radians, np.pi/180*degrees)

[2.61799388 6.28318531 1.57079633 0.78539816] [2.61799388 6.28318531 1.57079633 0.78539816]


In [ ]:
np.lcm(degrees, degrees * 3)

array([ 450, 1080,  270,  135])